apiVersion: v1
kind: PersistentVolume
metadata:
  name: predefined-volumetest
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: predefined-pvc
    namespace: local-path-storage
  hostPath:
    path: /bulk/storagetest
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: predefined-pvc
  namespace: local-path-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: local-path-storage
spec:
  containers:
  - name: volume-test
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: predefpvc