apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hopsa
  namespace: local-path-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: local-path-storage
spec:
  containers:
  - name: volume-test
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: hopsa